# docker-compose.prod.yml
networks:
  dispatchai-prod-network:
    external: true

services:
  frontend:
    image: ${PROD_FRONTEND_ECR}:${IMAGE_TAG}
    container_name: dispatchai-frontend-prod
    ports:
      - "3000:3000"
    restart: always
    networks:
      - dispatchai-prod-network
      
  api:
    image: ${PROD_BACKEND_API_ECR}:${IMAGE_TAG}
    container_name: dispatchai-api-prod
    env_file:
      - .env.prod
    environment:
      - SHOW_ERROR_MESSAGE=false
      - NODE_ENV=production
      - LOG_TO_FILE=true
    ports:
      - "4000:4000"
    restart: always
    networks:
      - dispatchai-prod-network

  ai:
    image: ${PROD_BACKEND_AI_ECR}:${IMAGE_TAG}
    container_name: dispatchai-ai-prod
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    restart: always
    networks:
      - dispatchai-prod-network

